[2025-04-28T17:03:05.070+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: earth_monitoring_system.run_dbt_transformations manual__2025-04-28T16:42:58.918391+00:00 [queued]>
[2025-04-28T17:03:05.100+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: earth_monitoring_system.run_dbt_transformations manual__2025-04-28T16:42:58.918391+00:00 [queued]>
[2025-04-28T17:03:05.100+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2025-04-28T17:03:05.140+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt_transformations> on 2025-04-28 16:42:58.918391+00:00
[2025-04-28T17:03:05.239+0000] {standard_task_runner.py:57} INFO - Started process 507 to run task
[2025-04-28T17:03:05.259+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'earth_monitoring_system', 'run_dbt_transformations', 'manual__2025-04-28T16:42:58.918391+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/earth_monitoring_dag.py', '--cfg-path', '/tmp/tmpc3x6_d9m']
[2025-04-28T17:03:05.277+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask run_dbt_transformations
[2025-04-28T17:03:05.370+0000] {logging_mixin.py:150} WARNING - /home/airflow/.local/lib/python3.10/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-28T17:03:05.560+0000] {task_command.py:410} INFO - Running <TaskInstance: earth_monitoring_system.run_dbt_transformations manual__2025-04-28T16:42:58.918391+00:00 [running]> on host 33402e959fd4
[2025-04-28T17:03:06.176+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='earth_monitoring_system' AIRFLOW_CTX_TASK_ID='run_dbt_transformations' AIRFLOW_CTX_EXECUTION_DATE='2025-04-28T16:42:58.918391+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-28T16:42:58.918391+00:00'
[2025-04-28T17:03:06.212+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-28T17:03:06.220+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/airflow/dbt && dbt run']
[2025-04-28T17:03:06.327+0000] {subprocess.py:86} INFO - Output:
[2025-04-28T17:03:06.446+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2025-04-28T17:03:06.449+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-04-28T17:03:06.638+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-04-28T17:03:06.649+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=earth_monitoring_system, task_id=run_dbt_transformations, execution_date=20250428T164258, start_date=20250428T170305, end_date=20250428T170306
[2025-04-28T17:03:06.708+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task run_dbt_transformations (Bash command failed. The command returned a non-zero exit code 127.; 507)
[2025-04-28T17:03:06.745+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-04-28T17:03:06.964+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
