[2025-04-26T23:19:36.748+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: earth_monitoring_system.run_dbt_transformations manual__2025-04-26T23:19:30.769066+00:00 [queued]>
[2025-04-26T23:19:36.759+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: earth_monitoring_system.run_dbt_transformations manual__2025-04-26T23:19:30.769066+00:00 [queued]>
[2025-04-26T23:19:36.759+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-04-26T23:19:36.778+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt_transformations> on 2025-04-26 23:19:30.769066+00:00
[2025-04-26T23:19:36.781+0000] {standard_task_runner.py:57} INFO - Started process 1371 to run task
[2025-04-26T23:19:36.784+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'earth_monitoring_system', 'run_dbt_transformations', 'manual__2025-04-26T23:19:30.769066+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/earth_monitoring_dag.py', '--cfg-path', '/tmp/tmpqnvsgdgm']
[2025-04-26T23:19:36.785+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask run_dbt_transformations
[2025-04-26T23:19:36.832+0000] {logging_mixin.py:150} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-26T23:19:36.949+0000] {task_command.py:410} INFO - Running <TaskInstance: earth_monitoring_system.run_dbt_transformations manual__2025-04-26T23:19:30.769066+00:00 [running]> on host d522fce2db24
[2025-04-26T23:19:37.203+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='earth_monitoring_system' AIRFLOW_CTX_TASK_ID='run_dbt_transformations' AIRFLOW_CTX_EXECUTION_DATE='2025-04-26T23:19:30.769066+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-26T23:19:30.769066+00:00'
[2025-04-26T23:19:37.204+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-26T23:19:37.205+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/airflow/dbt && dbt run']
[2025-04-26T23:19:37.211+0000] {subprocess.py:86} INFO - Output:
[2025-04-26T23:19:37.233+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2025-04-26T23:19:37.234+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-04-26T23:19:37.278+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-04-26T23:19:37.282+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=earth_monitoring_system, task_id=run_dbt_transformations, execution_date=20250426T231930, start_date=20250426T231936, end_date=20250426T231937
[2025-04-26T23:19:37.309+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 6 for task run_dbt_transformations (Bash command failed. The command returned a non-zero exit code 127.; 1371)
[2025-04-26T23:19:37.339+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-04-26T23:19:37.399+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
